- id: '1548858520404'
  alias: lunes_encendido
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.lunes_inicio.state[0:5]
      }}'
  condition:
  - condition: time
    weekday:
    - wed
  action:
  - data:
      entity_id: climate.termocasa
      operation_mode: heat
    service: climate.set_operation_mode
  - data_template:
      entity_id: climate.termocasa
      temperature: '{{ states.input_number.temperatura1.state }}'
    service: climate.set_temperature
- id: '1548858596334'
  alias: lunes_apagado
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.lunes_final.state[0:5]
      }}'
  condition:
  - condition: time
    weekday:
    - wed
  action:
  - data:
      entity_id: climate.termocasa
    service: climate.turn_off
- id: '1548858560404'
  alias: jueves_encendido
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.jueves_inicio.state[0:5]
      }}'
  condition:
  - condition: time
    weekday:
    - thu
  action:
  - data:
      entity_id: climate.termocasa
      operation_mode: heat
    service: climate.set_operation_mode
  - data_template:
      entity_id: climate.termocasa
      temperature: '{{ states.input_number.temperatura4.state }}'
    service: climate.set_temperature
- id: '1548858976334'
  alias: jueves_apagado
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.jueves_final.state[0:5]
      }}'
  condition:
  - condition: time
    weekday:
    - thu
  action:
  - data:
      entity_id: climate.termocasa
    service: climate.turn_off
- id: '1549270063295'
  alias: persiana1
  trigger:
  - entity_id: switch.shelly2
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.shelly21
    state: 'on'
  action:
  - data:
      entity_id: switch.shelly21
    service: switch.turn_off
- id: '1549270158138'
  alias: persiana2
  trigger:
  - entity_id: switch.shelly21
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.shelly2
    state: 'on'
  action:
  - data:
      entity_id: switch.shelly2
    service: switch.turn_off
- id: '1549277386478'
  alias: lastsee
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/presencia
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.occupancy == True }}'
  action:
  - data_template:
      payload_template: '{{ states.sensor.time.state }}'
      topic: sensor/presence
    service: mqtt.publish
  - data:
      entity_id: switch.luz_ofi
    service: switch.turn_on
- id: '1549257386478'
  alias: lastmotion
  trigger:
  - payload: 'ON'
    platform: mqtt
    topic: camera1/motion
  condition: []
  action:
  - data:
      payload_template: '{{ states.sensor.time.state }}'
      topic: cameras/time
    service: mqtt.publish
- id: '1549292034220'
  alias: alarma
  trigger:
  - entity_id: sensor.puerta_princ
    platform: state
    to: 'False'
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:E1:FA:8E
      ringtone_id: 0
      ringtone_vol: 100
    service: xiaomi_aqara.play_ringtone
  - data:
      message: Alarma activada!!
      data:
        actions:
        - action: desactivar
          title: Desactivar
        - action: nada
          title: Escopeta
    service: notify.android
- id: '1549272034220'
  alias: notificacion1
  trigger:
  - event_data:
      action: desactivar
    event_type: fcm_android_notifications.clicked
    platform: event
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:E1:FA:8E
    service: xiaomi_aqara.stop_ringtone
- id: '1549272035220'
  alias: notificacion2
  trigger:
  - event_data:
      action: nada
    event_type: fcm_android_notifications.clicked
    platform: event
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:E1:FA:8E
      ringtone_id: 5
      ringtone_vol: 50
    service: xiaomi_aqara.play_ringtone
- id: '1549292066320'
  alias: stop_alarma
  trigger:
  - entity_id: sensor.puerta_princ
    platform: state
    to: 'True'
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:E1:FA:8E
    service: xiaomi_aqara.stop_ringtone
- id: '1549292074220'
  alias: LOCK
  trigger:
  - payload: LOCK
    platform: mqtt
    topic: home/door/command
  action:
  - service: script.lock
- id: '1549292094220'
  alias: UNLOCK
  trigger:
  - payload: UNLOCK
    platform: mqtt
    topic: home/door/command
  condition: []
  action:
  - service: script.unlock
- id: '1549552712600'
  alias: tema
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: tema1
    service: frontend.set_theme
- id: '1549874296707'
  alias: incognito_on
  trigger:
  - entity_id: input_boolean.incognito
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: automation.alarma
    service: automation.turn_on
  - data:
      entity_id: automation.luz_encendido
    service: automation.turn_on
  - data:
      entity_id: automation.luz_apagado
    service: automation.turn_on
- id: '1549874296706'
  alias: incognito_off
  trigger:
  - entity_id: input_boolean.incognito
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: automation.alarma
    service: automation.turn_off
  - data:
      entity_id: automation.luz_encendido
    service: automation.turn_off
  - data:
      entity_id: automation.luz_apagado
    service: automation.turn_off
- id: '1547858520404'
  alias: luz_encendido
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.luces_encendido.state[0:5]
      }}'
  condition: []
  action:
  - data:
      entity_id: switch.luz_ofi
    service: switch.turn_on
- id: '1546858596334'
  alias: luz_apagado
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.luces_apagado.state[0:5]
      }}'
  condition: []
  action:
  - data:
      entity_id: switch.luz_ofi
    service: switch.turn_off
- id: '1550047650416'
  alias: alarma_calefaccion
  trigger:
  - entity_id: sensor.calefaccion_activa
    from: '0'
    platform: state
    to: '1'
  condition:
  - condition: state
    entity_id: sensor.puerta_princ
    state: 'False'
  action:
  - data:
      data:
        actions:
        - action: desact
          title: Desactivar
        - action: ok
          title: OK
      message: Calefaccion encendida con ventana abierta!
    service: notify.android
- id: '1549272034230'
  alias: notificacion2
  trigger:
  - event_data:
      action: desact
    event_type: fcm_android_notifications.clicked
    platform: event
  condition: []
  action:
  - data:
      entity_id: climate.termocasa
      operation_mode: auto
    service: climate.set_operation_mode
- id: '1550131587579'
  alias: alarma_on
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/pastilla
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.click == "single" }}'
  action:
  - data:
      payload: 'on'
      topic: hola
    service: mqtt.publish
- id: '1550131646503'
  alias: alarma_off
  trigger:
  - payload: 'on'
    platform: mqtt
    topic: hola
  condition: []
  action:
  - delay: 00:01:00
  - alias: ''
    data:
      payload: 'off'
      topic: hola
    service: mqtt.publish
- id: '1560131587579'
  alias: apagar_camara
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/pastilla
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.click == "long" }}'
  action:
  - data:
      payload: apagar
      topic: hola
    service: mqtt.publish
- id: '1550132125368'
  alias: cube_180
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "flip180" }}'
  action:
  - data:
      entity_id: switch.luz_ofi
    service: switch.toggle
- id: '1550132264167'
  alias: cube_90
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "flip90" }}'
  action:
  - data:
      entity_id: switch.shelly2
    service: switch.toggle
- id: '1550133849870'
  alias: apagado_luz
  trigger:
  - entity_id: sensor.presence
    for: 00:04:00
    platform: state
    to: 'False'
  condition: []
  action:
  - data:
      entity_id: switch.luz_ofi
    service: switch.turn_off
- id: '1550134893158'
  alias: inundacion
  trigger:
  - entity_id: sensor.water
    platform: state
    to: 'True'
  condition: []
  action:
  - data:
      message: Sensor de agua activado
    service: notify.android
- id: '1550140313287'
  alias: cubo_slide
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "slide" }}'
  action:
  - data:
      entity_id: light.gateway_light_7811dce1fa8e
    service: light.toggle
- id: '1550140695123'
  alias: mas_brillo
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "rotate_right" }}'
  - condition: state
    entity_id: light.gateway_light_7811dce1fa8e
    state: 'on'
  action:
  - data_template:
      entity_id: light.gateway_light_7811dce1fa8e
      brightness: '{{ states.light.gateway_light_7811dce1fa8e.attributes.brightness
        | int + 15 }}'
    service: light.turn_on
- id: '1550140696123'
  alias: menos_brillo
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "rotate_left" }}'
  - condition: state
    entity_id: light.gateway_light_7811dce1fa8e
    state: 'on'
  action:
  - data_template:
      entity_id: light.gateway_light_7811dce1fa8e
      brightness: '{{ states.light.gateway_light_7811dce1fa8e.attributes.brightness
        | int - 15 }}'
    service: light.turn_on
- id: '1550140685123'
  alias: mas_color
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "rotate_right" }}'
  - condition: state
    entity_id: light.gateway_light_7811dce1fa8e
    state: 'on'
  action:
  - data_template:
      entity_id: light.gateway_light_7811dce1fa8e
      hs_color:
      - '{{ (15 + (state_attr(''light.gateway_light_7811dce1fa8e'', ''hs_color'')[0]
        or 0)) % 360 }}'
      - 100
    service: light.turn_on
- id: '1550140675123'
  alias: menos_color
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "rotate_left" }}'
  - condition: state
    entity_id: light.gateway_light_7811dce1fa8e
    state: 'on'
  action:
  - data_template:
      entity_id: light.gateway_light_7811dce1fa8e
      hs_color:
      - '{{ ((state_attr(''light.gateway_light_7811dce1fa8e'', ''hs_color'')[0] or
        0) - 15) % 360 }}'
      - 100
    service: light.turn_on
- id: '1550340313287'
  alias: cubo_shake
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/cubo
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "shake" }}'
  action:
  - data:
      entity_id: automation.mas_brillo
    service: automation.toggle
  - data:
      entity_id: automation.menos_brillo
    service: automation.toggle
  - data:
      entity_id: automation.mas_color
    service: automation.toggle
  - data:
      entity_id: automation.menos_color
    service: automation.toggle
- id: '1551190664439'
  alias: bucle_on
  trigger:
  - entity_id: input_boolean.bucle
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:02:00
  - data_template:
      payload_template: '{{ states.sensor.precio_sum.state }}'
      topic: precio
    service: mqtt.publish
  - data:
      entity_id: input_boolean.bucle
    service: input_boolean.toggle
- id: '1551191161699'
  alias: bucle_off
  trigger:
  - entity_id: input_boolean.bucle
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - delay: 00:02:00
  - data_template:
      payload_template: '{{ states.sensor.precio_sum.state }}'
      topic: precio
    service: mqtt.publish
  - data:
      entity_id: input_boolean.bucle
    service: input_boolean.toggle
- id: '1551192334929'
  alias: bucle_start
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: input_boolean.bucle
    service: input_boolean.toggle
- id: '1551436117786'
  alias: open
  trigger:
  - entity_id: input_boolean.roller2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: cover.persian
    service: cover.open_cover
  - data:
      entity_id: input_boolean.roller3
    service: input_boolean.turn_off
  - data:
      payload: nada
      topic: shellies/shellyswitch-134A67/roller/0
    service: mqtt.publish
- id: '1551435117786'
  alias: open2
  trigger:
  - entity_id: input_boolean.roller3
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: cover.persian
    service: cover.close_cover
  - data:
      entity_id: input_boolean.roller2
    service: input_boolean.turn_off
  - data:
      payload: nada
      topic: shellies/shellyswitch-134A67/roller/0
    service: mqtt.publish
- id: '1551454965324'
  alias: open3
  trigger:
  - payload: stop
    platform: mqtt
    topic: shellies/shellyswitch-134A67/roller/0
  condition: []
  action:
  - data:
      entity_id: input_boolean.roller2
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.roller3
    service: input_boolean.turn_off
- id: '1551714261598'
  alias: consumo_dia
  trigger:
  - at: '23:59:00'
    platform: time
  condition: []
  action:
  - data:
      payload: 20
      topic: consumo/dia
    service: mqtt.publish
  - data: {}
    service: script.mes
- id: '1551715628795'
  alias: loop
  trigger:
  - platform: time_pattern
    minutes: /2
  condition: []
  action:
  - service: script.dia
